#!/bin/sh
set -e
cd $(dirname $0)

pkgs="bytestring-progress hashable hashmap binary haskell-src-exts unordered-containers uniplate derive"

mkdir -p dependencies

cd dependencies
for pkg in $pkgs; do
   if [ ! -d $pkg* ]; then
       cabal unpack $pkg
   fi
done
cd ..

if [ $no_install ]; then
    scripts/fetch-minisat dependencies/minisat
    exit 0
fi

dir=$(mktemp -d -t jukeboxXXX)

if [ ! $mode ]; then
   export package_db=$dir/pkgs
   ghc-pkg init $package_db
   export cabal_opts="--user --prefix=$package_db --package-db=$package_db"
else
   export cabal_opts=--$mode
fi
scripts/install-minisat

for pkg in $pkgs; do
    cd dependencies/$pkg*
    runhaskell Setup.* configure $cabal_opts
    runhaskell Setup.* build
    runhaskell Setup.* install
    cd ../..
done

runhaskell Setup.* configure $cabal_opts --bindir=.
runhaskell Setup.* build
runhaskell Setup.* install
rm -r $dir
