#!/bin/sh
set -e
cd $(dirname $0)

pkgs="random QuickCheck alex cpphs deepseq transformers mtl happy text bytestring-progress hashable hashmap binary haskell-src-exts unordered-containers syb uniplate derive"

mkdir -p dependencies

cd dependencies
for pkg in $pkgs; do
   if [ ! -d $pkg* ]; then
       cabal unpack $pkg
   fi
done
cd ..

if [ $no_install ]; then
    scripts/fetch-minisat dependencies/minisat
    exit 0
fi

dir=$(mktemp -d -t jukeboxXXX)

if [ ! $mode ]; then
   export package_db=$dir/pkgs
   ghc-pkg init $package_db
   export cabal_opts="--user --prefix=$package_db --package-db=$package_db"
   export ghcpkg_opts="-f $package_db"
   export PATH=$package_db/bin:$PATH
else
   export cabal_opts=--$mode
fi
scripts/install-minisat

for pkg in $pkgs; do
    cd dependencies/$pkg*
    runhaskell Setup.* configure $cabal_opts
    runhaskell Setup.* build
    runhaskell Setup.* install
    cd ../..
done

p=$(ghc-pkg $ghcpkg_opts describe minisat|grep '^library-dirs: '|awk '{print $2;}')
export LD_LIBRARY_PATH=$p
export DYLD_LIBRARY_PATH=$p
runhaskell Setup.* configure $cabal_opts --bindir=.
runhaskell Setup.* build
runhaskell Setup.* install
rm -r $dir
