#!/bin/sh
set -e

if [ $# != 0 ]; then
    echo install-minisat doesn\'t take any arguments: use environment variables instead
    exit 1
fi

if [ ! $prefix ]; then prefix=$(pwd)/minisat; fi
if [ ! $mode ]; then mode=user; fi
if [ x$mode = xglobal ]; then
    if [ ! $sudo ] && [ $USER != root ]; then sudo=sudo; fi
else
    if [ ! $sudo ]; then sudo=; fi
fi
export prefix

dir=$(mktemp -d -t minisatXXX)
if [ -d minisat/src ]; then
    cp -r minisat/src/minisat $dir/minisat
    cp -r minisat/src/c $dir/c
    cp -r minisat/src/haskell $dir/haskell
else
    git clone git://github.com/niklasso/minisat.git $dir/minisat
    git clone git://github.com/niklasso/minisat-c-bindings.git $dir/c
    git clone git://github.com/niklasso/minisat-haskell-bindings.git $dir/haskell
fi

make -C $dir/minisat
$sudo make -C $dir/minisat install

export MINISAT_INCLUDE=-I$prefix/include
export MINISAT_LIB="-L$prefix/lib -lminisat"

make -C $dir/c
$sudo make -C $dir/c install

cd $dir/haskell && $sudo cabal install --extra-include-dirs=$prefix/include --extra-lib-dirs=$prefix/lib --$mode -p
$sudo rm -rf $dir/*/.git
$sudo rm -r $dir
