#!/bin/sh
set -e
mkdir scratch
cd scratch
git clone .. jukebox
dir=jukebox/minisat/src
mkdir -p $dir
git clone git://github.com/niklasso/minisat.git $dir/minisat
git clone git://github.com/niklasso/minisat-c-bindings.git $dir/c
git clone git://github.com/niklasso/minisat-haskell-bindings.git $dir/haskell
rm -rf jukebox/.git $dir/minisat/.git $dir/c/.git $dir/haskell/.git
tar czvf jukebox.tar.gz jukebox
cd ..
mv scratch/jukebox.tar.gz .
rm -r scratch
if [ x$1 = xupload ]; then
    scp jukebox.tar.gz nicsma@remote11.chalmers.se:www/www.cse.chalmers.se
    ssh nicsma@remote11.chalmers.se chmod a+r www/www.cse.chalmers.se/jukebox.tar.gz
fi
